### ISSUE TITLE
device-info is not working on the raspberry pi and unity8 will not start 

### ISSUE THREAD

**Issue by wouter182** [ubports/deviceinfo#1]
"device-info" is not working on the raspberry pi. It is executed in the start of unity8 such that the error below is also in the unity8 log and it prevents it from starting unity8.

phablet@ubuntu-phablet:~$ device-info 
library "libcutils.so" not found
failed to load bionic libc.so
Aborted

Strace https://paste.ubuntu.com/p/q7RK6gBTvS/
libandroid-properties1 is installed by default in the pi image
Installing libandroid-properties-dev makes no difference

It is unknown if this is a bug or that it is missing a config file like pine/librem.
In both cases it prevents unity8 from starting.

**Comment by Flohack74** [comment]
Well that points to not having Android libs available (hint about bionic libc), and thats probably correct but actually in my rootfs this command does not even exist. Which rootfs are you using?

**Comment by wouter182** [comment]
_Which rootfs are you using?_
rootfs-rpi build number #56
http://ci.ubports.com/job/rootfs/job/rootfs-rpi/56/
In build #44 which has no problems, it ended in the log with line 88 from src/config.cpp: Log::info("No device config found!");

**Comment by mariogrip** [comment]
oh! this comes after a update to libhybris, older version of libhybris implemented the properties themself, but the newer one uses android libs to do it.

**Comment by wouter182** [comment]
Okay, so you mean that we have to add these libs for a proper working of the raspberry pi rootfs?
It looks like it needs at least: libc.so libcutils.so liblog.so.0 libpthread.so.0 based on running device-info with strace.
Is there a good source for these libs?
I think this effects all mainline devices, so is it an idea to add these to mainline?
I tried to solve this myself but I am not familiar with android.

**Comment by wouter182** [comment]
solved
